### ISSUE TITLE
Segmentation backfill running from oldest GA event data plus interval date.

### ISSUE THREAD

**Issue by danchapman** [GoogleCloudPlatform/marketing-analytics-jumpstart#33]
For the segmentation data backfills, the start of the date range for the look back is running from the earliest data that has GA data available plus the number look back interval days. This range doesn't seem like what we want to train on. It seems like we would want to backfill on the current date, minus the number of days in the look back interval.

This line of SQL determines the start date:
https://github.com/GoogleCloudPlatform/marketing-data-engine/blob/37c5635af74c2ffe7794496a7244a947d8440a55/sql/query/invoke_backfill_user_segmentation_dimensions.sqlx#L20

**For instance, as of now, given these parameters:**
GA data available in BQ : 7/19/23 - 8/9/23
Interval Min Date : 15
The backfill SQL populates with a start date of : 8/3/23
This would only give us 6 days of data.

**What I would expect:**
GA data available in BQ : 7/19/23 - 8/9/23
Interval Min Date : 15
The backfill SQL populates with a start date of : 7/26/23
This would give us 15 days of data.

If I'm misunderstanding what data should be available after the backfill let me know, but right now it's trimming what could be useful input data.

**Comment by chmstimoteo** [comment]
This issue is being addressed by a new PR #35 that I'm opening.

**Comment by chmstimoteo** [comment]
@danchapman the way the backfill dates are calculated now, this is the range:
![image](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/assets/16627815/16af5ca8-3236-4d0c-aa99-7ba01c80b394)

What you're proposing is:
![image](https://github.com/GoogleCloudPlatform/marketing-analytics-jumpstart/assets/16627815/adb5f37a-28d0-4736-8638-186971618062)

It is not 15 days of data that your logic returns. Because we only have 22 days of data and we need to lookback (for segmentation) 15 days of interval. We can only give 7 steps in the past until we get to the beginning of the interval.
